name: crcns-python
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - python=3
  - numpy
  - matplotlib
  - pandas
  - pyqt

  # Jupyter Environment
  - notebook
  - ipython

  - pip:
      # Neuro stuff
      - '-e git+https://github.com/mne-tools/mne-python.git@master'
      - '-e git+https://github.com/choldgraf/mne-spikes.git@master'

      # Utilities
      - download
      - nbgrader
      - tqdm

      # Auditory analysis
      - librosa
