name: crcns-python
channels:
  - conda-forge
dependencies:
  # Core scientific python
  - python=3
  - numpy
  - matplotlib
  - pandas
  - pyqt

  # Jupyter Environment
  - notebook
  - ipython
  - jupyter_contrib_nbextensions

  - pip:
      # Neuro stuff
      -e git://github.com/mne-tools/mne-python.git#egg=mne
      -e git://github.com/choldgraf/mne-spikes.git#egg=mnespikes

      # Utilities
      - download
      - nbgrader
      - tqdm
      
      